### PR TITLE
Update to compile under Rust 1.36 (Stable)

### PR DESCRIPTION
**Pull request by jespersm**
I think this should be enough compile under Rust 1.36.0.

### CODE REVIEW

**Comment by jespersm** [comment]
I fixed the commit to make it slightly cleaner.

**Comment by mmitteregger** [comment]
Hi, thanks for the pull request, but I wasn't planning on using stable yet - sorry.

I am not quite happy with the current implementation regarding when a function parameter is considered to be from scenario data versus to be a step argument.
Currently the first argument is unconditionally considered to be from scenario data and I was considering using an [function parameter attribute](https://github.com/rust-lang/rust/issues/60406) to denote scenario data parameters like
```rust
pub fn reset_calculator(#[scenario] calc: &mut Calc) {
    // ...
}
```
That way there may be multiple scenario data arguments or none at all.

I will be creating a stable branch with your commit so that you could use that if you'd like, but I am not planning on maintaining it. As you can see yourself I am not as actively working on the project as I'd like to.

**Comment by jespersm** [comment]
Nice. Well, you might not be entirely happy with it, but I've found the library super useful as is -- so thanks!

**Comment by mmitteregger** [comment]
I have updated the code to work with the latest stable compiler `1.46.0`.
Now that this is finally complete I am going to close this PR and will delete the `stable` branch.

Thank you.

**Pull request closed without merging**
